# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37740ad3de6be151e2a90adfa206fe6c8759b02a9ff87e9b5752f5fde2034a46a1ad79d347801efae11ed4a217b2e00be6229a83da552f33aa20fce2d11e47e4

test:
  secret_key_base: b4db3d6fc7575248b1a50c48df513d14d5c46c5bed639ce507ed8b502273a7e4c42ddf1183af27f4d266a602d93f63ea041ad4ab3a08bd6a3ddb59fa08313eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
